# Generated by Django 4.0.1 on 2022-02-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_shippingcost_order_shippingprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shippingCost',
            new_name='shippingPrice',
        ),
    ]
