# Generated by Django 4.0.1 on 2022-02-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
