# Generated by Django 4.0.1 on 2022-02-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
