# Generated by Django 4.0.1 on 2022-02-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_review_city_review_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
    ]
